default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: techraids_development

test:
  <<: *default
  database: techraids_test

production:
  primary: &primary_production
    <<: *default
    database: techraids_production
  cache:
    <<: *primary_production
    database: techraids_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: techraids_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: techraids_production_cable
    migrations_paths: db/cable_migrate
